#!/usr/bin/env bash
# Install nginx on the server
sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
