#!/usr/bin/env bash
# Redirect to another page
apt-get update
apt-get -y install nginx
chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/\tserver_name _;/a \\n\tlocation /redirect_me {\n\t\trewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}' /etc/nginx/sites-available/default
service nginx restart
